version: '3.5'

services:
  postgre-vs-mongo:
    image: postgre-vs-mongo
    build: .
    depends_on:
      - pg
      - mongo
    environment:
      NODE_ENV: development
    volumes: 
      - .:/usr/src/app
      - /usr/src/app/node_modules    
    ports:
      - 3000:3000 
  pg:
    image: postgres:11.2
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: test
  mongo: 
    image: mongo:4.0.7
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: test